// Six-segment graft (final approved build) — byte-preserving graft + radial-
// field pass. Segment03 comes verbatim from the seg36 rollout GLB
// (regenerated by validate_ring_collapse_seg36_rollout.py), Segment06 from
// the seg06-simplified rollout GLB (regenerated by
// validate_ring_collapse_seg06_simplified_rollout.py).
//
// Step 1 (GRAFT): appends the two harmonized new roots
// (Segment03/06_Cracked_BALANCED from the seg36 rollout GLB) into the
// approved seam-corridor-final-fix GLB WITHOUT touching a single approved
// byte: the approved bin is the verbatim prefix of the new bin, every
// approved JSON array is a verbatim prefix of the new array. Shared
// materials are mapped BY NAME onto the approved material indices; only
// M_Fracture_Cracked_C (+ its 3 atlas textures/images) is appended.
//
// Step 2 (FIELD): the four approved normal passes compose — for cracked
// tops — to one end state: every pure-horizontal plateau vert of
// M_ArenaTop_Val carries the EXACT intact radial-field normal; every
// damage-adjacent vert keeps its harmonized/crack normal. That end state is
// applied to the two new roots in one pass (in-place patch of their two
// NORMAL accessors, which live in the appended region — approved bytes
// remain untouched by construction).
//
// Prerequisite chain (run in this order first):
//   1. validate_ring_collapse_seg36_gate.py        -> seg36_gate.glb + pair-3 atlas
//   2. validate_ring_collapse_seg36_rollout.py      -> seg36_rollout.glb
//   3. validate_ring_collapse_seg06_simplified_gate.py    -> seg06_simplified.glb
//   4. validate_ring_collapse_seg06_simplified_rollout.py -> seg06_simplified_rollout.glb
//
// Run:  node tools/ring_collapse/graft_simplified.js
'use strict';
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..', '..');
const SRC_A = path.join(ROOT, 'assets/ring_collapse/validation/seam_corridor_final_fix/ring_collapse_seam_corridor_final_fix.glb');
const SRC_P = path.join(ROOT, 'assets/ring_collapse/validation/seg36_rollout/ring_collapse_seg36_rollout.glb');
const SRC_F = path.join(ROOT, 'assets/ring_collapse/validation/seg36_rollout/ring_collapse_seg06_simplified_rollout.glb');
const DSTDIR = path.join(ROOT, 'assets/ring_collapse/validation/six_segment_rollout');
const DST = path.join(DSTDIR, 'ring_collapse_six_segment_simplified.glb');
const STATS_OUT = path.join(ROOT, 'artifacts/ring_collapse/six_segment_rollout/simplified_graft_stats.json');

const SEG_BOUNDS_DEG = [10, 72, 128, 183, 255, 308];
const NEW_ROOTS = ['Segment03_Cracked_BALANCED', 'Segment06_Cracked_BALANCED'];
const INTACT = ['Segment01_Intact', 'Segment02_Intact', 'Segment03_Intact',
                'Segment04_Intact', 'Segment05_Intact', 'Segment06_Intact'];
const assert = (c, m) => { if (!c) throw new Error('GRAFT ABORT: ' + m); };

function loadGLB(fp) {
  const g = fs.readFileSync(fp);
  assert(g.readUInt32LE(0) === 0x46546c67, 'not a GLB: ' + fp);
  const jl = g.readUInt32LE(12);
  return { json: JSON.parse(g.slice(20, 20 + jl).toString('utf8')),
           bin: g.slice(20 + jl + 8, 20 + jl + 8 + g.readUInt32LE(20 + jl)) };
}
const A = loadGLB(SRC_A);
const P_OLD = loadGLB(SRC_P);
const P_FIX = loadGLB(SRC_F);
let P = P_FIX;   // active import source (seg06 first: its material C wins)

// ── step 1: graft ──────────────────────────────────────────────────────────
const out = JSON.parse(JSON.stringify(A.json));      // approved JSON, extended
const matByName = {};
out.materials.forEach((m, i) => { matByName[m.name] = i; });
const texOfs = out.textures.length, imgOfs = out.images.length;
const bvOfs = out.bufferViews.length, accOfs = out.accessors.length;
const samOfs = (out.samplers || []).length;

// appended bin: approved bin verbatim, then the pair's bufferViews packed
const parts = [A.bin];
let cursor = A.bin.length;
const pad = () => { const p = (4 - (cursor % 4)) % 4;
  if (p) { parts.push(Buffer.alloc(p)); cursor += p; } };
const bvMap = new Map();          // pair bv index -> new bv index
function importBV(i) {
  if (bvMap.has(i)) return bvMap.get(i);
  const bv = P.json.bufferViews[i];
  pad();
  const data = P.bin.slice(bv.byteOffset || 0, (bv.byteOffset || 0) + bv.byteLength);
  const nbv = { buffer: 0, byteOffset: cursor, byteLength: bv.byteLength };
  if (bv.byteStride !== undefined) nbv.byteStride = bv.byteStride;
  parts.push(data); cursor += bv.byteLength;
  out.bufferViews.push(nbv);
  bvMap.set(i, out.bufferViews.length - 1);
  return out.bufferViews.length - 1;
}
const accMap = new Map();
function importAcc(i) {
  if (accMap.has(i)) return accMap.get(i);
  const a = JSON.parse(JSON.stringify(P.json.accessors[i]));
  a.bufferView = importBV(a.bufferView);
  out.accessors.push(a);
  accMap.set(i, out.accessors.length - 1);
  return out.accessors.length - 1;
}
const samMap = new Map();
function importSampler(i) {
  if (i === undefined) return undefined;
  if (samMap.has(i)) return samMap.get(i);
  out.samplers = out.samplers || [];
  out.samplers.push(JSON.parse(JSON.stringify(P.json.samplers[i])));
  samMap.set(i, out.samplers.length - 1);
  return out.samplers.length - 1;
}
const imgMap = new Map();
function importImage(i) {
  if (imgMap.has(i)) return imgMap.get(i);
  const im = JSON.parse(JSON.stringify(P.json.images[i]));
  im.bufferView = importBV(im.bufferView);
  out.images.push(im);
  imgMap.set(i, out.images.length - 1);
  return out.images.length - 1;
}
const texMap = new Map();
function importTexture(i) {
  if (texMap.has(i)) return texMap.get(i);
  const t = JSON.parse(JSON.stringify(P.json.textures[i]));
  if (t.source !== undefined) t.source = importImage(t.source);
  if (t.sampler !== undefined) t.sampler = importSampler(t.sampler);
  out.textures.push(t);
  texMap.set(i, out.textures.length - 1);
  return out.textures.length - 1;
}
function importMaterial(i) {
  const name = P.json.materials[i].name;
  if (name in matByName) return matByName[name];
  assert(name === 'M_Fracture_Cracked_C', 'unexpected new material ' + name);
  const m = JSON.parse(JSON.stringify(P.json.materials[i]));
  const fixTex = ref => { if (ref && ref.index !== undefined) ref.index = importTexture(ref.index); };
  if (m.pbrMetallicRoughness) {
    fixTex(m.pbrMetallicRoughness.baseColorTexture);
    fixTex(m.pbrMetallicRoughness.metallicRoughnessTexture);
  }
  fixTex(m.normalTexture); fixTex(m.occlusionTexture); fixTex(m.emissiveTexture);
  out.materials.push(m);
  matByName[name] = out.materials.length - 1;
  return matByName[name];
}

const addedNodes = [];
const SRC_FOR = { 'Segment06_Cracked_BALANCED': P_FIX,
                  'Segment03_Cracked_BALANCED': P_OLD };
for (const rootName of ['Segment06_Cracked_BALANCED', 'Segment03_Cracked_BALANCED']) {
  P = SRC_FOR[rootName];
  bvMap.clear(); accMap.clear(); samMap.clear(); imgMap.clear(); texMap.clear();
  const pNode = P.json.nodes.find(n => n.name === rootName);
  assert(pNode && pNode.mesh !== undefined, rootName + ' missing in pair GLB');
  const pMesh = P.json.meshes[pNode.mesh];
  const mesh = { name: pMesh.name, primitives: [] };
  for (const prim of pMesh.primitives) {
    const np = { attributes: {}, mode: prim.mode };
    for (const [k, ai] of Object.entries(prim.attributes)) np.attributes[k] = importAcc(ai);
    np.indices = importAcc(prim.indices);
    np.material = importMaterial(prim.material);
    if (np.mode === undefined) delete np.mode;
    mesh.primitives.push(np);
  }
  out.meshes.push(mesh);
  const node = { name: pNode.name, mesh: out.meshes.length - 1 };
  if (pNode.translation) node.translation = pNode.translation;
  out.nodes.push(node);
  addedNodes.push(out.nodes.length - 1);
}
out.scenes[0].nodes.push(...addedNodes);
pad();
const newBin = Buffer.concat(parts);
out.buffers[0].byteLength = newBin.length;

// self-verify prefix properties
assert(newBin.slice(0, A.bin.length).equals(A.bin), 'approved bin not a prefix');
for (const key of ['bufferViews', 'accessors', 'materials', 'textures', 'images', 'meshes', 'nodes'])
  assert(JSON.stringify(out[key].slice(0, A.json[key].length)) ===
         JSON.stringify(A.json[key]), key + ' prefix changed');

// ── step 2: field pass on the two new roots (operates on `out`/`newBin`) ──
const matName = i => out.materials[i].name;
const nodeOf = n => out.nodes.find(x => x.name === n);
function accF32(idx) {
  const a = out.accessors[idx], bv = out.bufferViews[a.bufferView];
  const off = (bv.byteOffset || 0) + (a.byteOffset || 0);
  const n = { SCALAR: 1, VEC2: 2, VEC3: 3 }[a.type];
  return new Float32Array(newBin.buffer, newBin.byteOffset + off, a.count * n);
}
function accIdx(idx) {
  const a = out.accessors[idx], bv = out.bufferViews[a.bufferView];
  const off = (bv.byteOffset || 0) + (a.byteOffset || 0);
  return a.componentType === 5123 ? new Uint16Array(newBin.buffer, newBin.byteOffset + off, a.count)
                                  : new Uint32Array(newBin.buffer, newBin.byteOffset + off, a.count);
}
function classify(nm) {
  const node = nodeOf(nm);
  const prim = out.meshes[node.mesh].primitives.find(p => matName(p.material) === 'M_ArenaTop_Val');
  const Pv = accF32(prim.attributes.POSITION);
  const I = accIdx(prim.indices);
  const nv = Pv.length / 3;
  let yMax = -1e9; for (let i = 1; i < Pv.length; i += 3) yMax = Math.max(yMax, Pv[i]);
  const horizAdj = new Uint8Array(nv), damageAdj = new Uint8Array(nv);
  for (let f = 0; f < I.length; f += 3) {
    const tri = [I[f], I[f+1], I[f+2]];
    const pa = Pv.subarray(tri[0]*3, tri[0]*3+3), pb = Pv.subarray(tri[1]*3, tri[1]*3+3), pc = Pv.subarray(tri[2]*3, tri[2]*3+3);
    const cx = (pb[1]-pa[1])*(pc[2]-pa[2])-(pb[2]-pa[2])*(pc[1]-pa[1]);
    const cy = (pb[2]-pa[2])*(pc[0]-pa[0])-(pb[0]-pa[0])*(pc[2]-pa[2]);
    const cz = (pb[0]-pa[0])*(pc[1]-pa[1])-(pb[1]-pa[1])*(pc[0]-pa[0]);
    const l = Math.hypot(cx, cy, cz); if (l < 2e-12) continue;
    const isPlateau = cy/l > 0.9 && (pa[1]+pb[1]+pc[1])/3 > yMax - 0.02;
    for (const v of tri) (isPlateau ? horizAdj : damageAdj)[v] = 1;
  }
  return { node, prim, P: Pv, horizAdj, damageAdj };
}
const knots = new Map();
for (const nm of INTACT) {
  const { node, prim, P: Pv, horizAdj } = classify(nm);
  const N = accF32(prim.attributes.NORMAL);
  const t = node.translation;
  for (let i = 0; i < Pv.length / 3; i++) {
    if (!horizAdj[i]) continue;
    const wx = Pv[3*i]+t[0], wz = Pv[3*i+2]+t[2], r = Math.hypot(wx, wz);
    const k = r.toFixed(3);
    if (!knots.has(k)) knots.set(k, []);
    knots.get(k).push(Math.atan2(N[3*i]*wx/r + N[3*i+2]*wz/r, N[3*i+1]));
  }
}
const profile = [...knots.entries()].filter(([, v]) => v.length >= 50)
  .map(([k, v]) => [parseFloat(k), v.reduce((a, b) => a + b, 0)/v.length]).sort((a, b) => a[0]-b[0]);
assert(profile.length === 6, 'expected 6 intact loop radii, got ' + profile.length);
const fieldTilt = r => {
  if (r <= profile[0][0]) return profile[0][1];
  for (let i = 1; i < profile.length; i++) if (r <= profile[i][0]) {
    const t = (r-profile[i-1][0])/(profile[i][0]-profile[i-1][0]);
    return profile[i-1][1]*(1-t)+profile[i][1]*t;
  }
  return profile[profile.length-1][1];
};

const stats = { profile: profile.map(([r, t]) => ({ r, tilt_deg: +(t*180/Math.PI).toFixed(3) })),
  segments: {}, graft: { appended_bufferViews: out.bufferViews.length - bvOfs,
    appended_accessors: out.accessors.length - accOfs,
    appended_images: out.images.length - imgOfs,
    appended_textures: out.textures.length - texOfs,
    appended_materials: out.materials.length - A.json.materials.length } };
const dot = (a, b) => a[0]*b[0]+a[1]*b[1]+a[2]*b[2];
const angDeg = (a, b) => Math.acos(Math.min(1, Math.max(-1, dot(a, b)))) * 180 / Math.PI;
for (const nm of NEW_ROOTS) {
  const { node, prim, P: Pv, horizAdj, damageAdj } = classify(nm);
  const N = accF32(prim.attributes.NORMAL);
  const t = node.translation;
  let changed = 0, kept = 0, sum = 0, mx = 0;
  for (let i = 0; i < Pv.length / 3; i++) {
    if (!horizAdj[i]) continue;
    if (damageAdj[i]) { kept++; continue; }
    const wx = Pv[3*i]+t[0], wz = Pv[3*i+2]+t[2], r = Math.hypot(wx, wz);
    const a = fieldTilt(r);
    const tgt = [wx/r*Math.sin(a), Math.cos(a), wz/r*Math.sin(a)];
    const l = Math.hypot(...tgt);
    tgt[0] /= l; tgt[1] /= l; tgt[2] /= l;
    const old = [N[3*i], N[3*i+1], N[3*i+2]];
    const lo = Math.hypot(...old) || 1;
    const chg = angDeg([old[0]/lo, old[1]/lo, old[2]/lo], tgt);
    if (chg < 0.005) continue;
    N[3*i] = tgt[0]; N[3*i+1] = tgt[1]; N[3*i+2] = tgt[2];
    changed++; sum += chg; if (chg > mx) mx = chg;
  }
  stats.segments[nm] = { changed_loops: changed, kept_damage_adjacent: kept,
    mean_change_deg: +(sum/(changed || 1)).toFixed(3), max_change_deg: +mx.toFixed(3) };
  console.log(`${nm}: field pass changed ${changed} pure-horizontal loops (kept damage-adjacent ${kept}) · mean ${(sum/(changed||1)).toFixed(2)}deg max ${mx.toFixed(2)}deg`);
}

// ── step 3: taper micro-split census snap (Segment06 only) ────────────────
// The gold-taper's theta-dependent end rotation separates formerly
// coincident vertices by ~1e-4; the weld census (1e-5 grid) then counts the
// adjacent edges as open. Snap open-census vertex pairs closer than 0.5 mm
// back onto one shared position — pure position equalization inside the
// rebuilt root (normals, indices and every approved root untouched).
{
  const nm = 'Segment06_Cracked_BALANCED';
  const node = nodeOf(nm);
  const prims = out.meshes[node.mesh].primitives;
  const views = prims.map(p => ({ P: accF32(p.attributes.POSITION),
                                  I: accIdx(p.indices) }));
  const keyOf = (x, y, z) =>
    Math.round(x / 1e-5) + ',' + Math.round(y / 1e-5) + ',' + Math.round(z / 1e-5);
  const census = () => {
    const ecount = new Map();
    for (const { P, I } of views) {
      for (let f = 0; f < I.length; f += 3) {
        const ks = [I[f], I[f + 1], I[f + 2]].map(
          v => keyOf(P[3 * v], P[3 * v + 1], P[3 * v + 2]));
        for (let e = 0; e < 3; e++) {
          const a = ks[e], b = ks[(e + 1) % 3];
          if (a === b) continue;
          const ek = a < b ? a + '|' + b : b + '|' + a;
          ecount.set(ek, (ecount.get(ek) || 0) + 1);
        }
      }
    }
    const open = [];
    for (const [ek, c] of ecount) if (c === 1) open.push(ek);
    return open;
  };
  const before = census();
  const openKeys = new Map();
  for (const ek of before)
    for (const k of ek.split('|'))
      if (!openKeys.has(k))
        openKeys.set(k, k.split(',').map(v => Number(v) * 1e-5));
  const keys = [...openKeys.entries()];
  const snapTo = new Map();
  for (let i = 0; i < keys.length; i++) {
    if (snapTo.has(keys[i][0])) continue;
    for (let j = i + 1; j < keys.length; j++) {
      if (snapTo.has(keys[j][0])) continue;
      const a = keys[i][1], b = keys[j][1];
      const d = Math.hypot(a[0] - b[0], a[1] - b[1], a[2] - b[2]);
      if (d > 0 && d <= 5e-4) snapTo.set(keys[j][0], keys[i][0]);
    }
  }
  // canonical positions: exact float32 values of the snap target key's verts
  const keyPos = new Map();
  for (const { P } of views)
    for (let i = 0; i < P.length / 3; i++) {
      const k = keyOf(P[3 * i], P[3 * i + 1], P[3 * i + 2]);
      if (!keyPos.has(k)) keyPos.set(k, [P[3 * i], P[3 * i + 1], P[3 * i + 2]]);
    }
  let moved = 0;
  for (const { P } of views)
    for (let i = 0; i < P.length / 3; i++) {
      const k = keyOf(P[3 * i], P[3 * i + 1], P[3 * i + 2]);
      const tk = snapTo.get(k);
      if (!tk) continue;
      const t = keyPos.get(tk);
      P[3 * i] = t[0]; P[3 * i + 1] = t[1]; P[3 * i + 2] = t[2];
      moved++;
    }
  const after = census();
  stats.seg06_census_snap = { open_edges_before: before.length,
    open_edges_after: after.length, vert_instances_moved: moved,
    pairs_snapped: snapTo.size };
  console.log(`seg06 census snap: open edges ${before.length} -> ${after.length}` +
    ` · ${snapTo.size} pairs · ${moved} vertex instances (<=0.5mm)`);
}

// approved region untouched by the field pass (normals live in appended bvs)
assert(newBin.slice(0, A.bin.length).equals(A.bin), 'approved bin changed by field pass');

// ── write ──────────────────────────────────────────────────────────────────
let jsonBuf = Buffer.from(JSON.stringify(out), 'utf8');
const jpad = (4 - (jsonBuf.length % 4)) % 4;
if (jpad) jsonBuf = Buffer.concat([jsonBuf, Buffer.from(' '.repeat(jpad))]);
const total = 12 + 8 + jsonBuf.length + 8 + newBin.length;
const head = Buffer.alloc(20);
head.writeUInt32LE(0x46546c67, 0); head.writeUInt32LE(2, 4); head.writeUInt32LE(total, 8);
head.writeUInt32LE(jsonBuf.length, 12); head.writeUInt32LE(0x4e4f534a, 16);
const binHead = Buffer.alloc(8);
binHead.writeUInt32LE(newBin.length, 0); binHead.writeUInt32LE(0x004e4942, 4);
fs.mkdirSync(DSTDIR, { recursive: true });
fs.writeFileSync(DST, Buffer.concat([head, jsonBuf, binHead, newBin]));
console.log(`written ${path.basename(DST)} (${(total/1e6).toFixed(2)} MB) · 12 roots · ` +
  `appended: ${stats.graft.appended_bufferViews} bvs, ${stats.graft.appended_accessors} accs, ` +
  `${stats.graft.appended_images} images, ${stats.graft.appended_materials} material(s)`);
fs.mkdirSync(path.dirname(STATS_OUT), { recursive: true });
fs.writeFileSync(STATS_OUT, JSON.stringify(stats, null, 1));
